#!/bin/bash
# Script : sync-personal-pools
# Date : 06/12/2025
# Version proxmox : 9.0
# Description :
#   - Crée un pool par membre du groupe dans $GROUP s’il n’existe pas
#   - Assigne le role dans $ROLE
#   - Marque les pools à supprimer pour les membres n'étant plus dans le groupe
#   - Eteint les VMs des etudiants plus membres
# ----------------------------------------------------------------------

GROUP="proxmox-etudiant"     		# Nom du groupe AD
ROLE="etudiant"              		# Rôle Proxmox attribué à chaque étudiant
PREFIX="etudiant-"           		# Préfixe des pool
REALM="adsio"                		# Nom du realm AD dans Proxmox
RMPREFIX="removed-"         		# Préfixe des pool supprimés
TMPFILE="/tmp/sync-personnal-pool"  # Fichier temporaire de travail


# Paramètre passé
if [[ -n "$1" ]]; then
    if [[ "$1" == "-h" ]]; then
        echo "Usage: $0 [groupe]"
        exit 0
    else
        GROUP="proxmox-$1"
		ROLE="$1"
		PREFIX="$1-"
    fi
fi


echo "[$(date)] Synchronisation des pools des membres ($GROUP@$REALM)"

#Vérification  de l'existence du groupe
if ! pveum group list | grep -q "$GROUP-$REALM"; then
  echo "Erreur : Groupe $GROUP@$REALM introuvable!"
  exit 1
fi

# Récupération des membres du groupe
pvesh get /access/groups --human-readable 0 --noborder | grep "$GROUP-$REALM"| awk '{print $2}' | tr ',' '\n' > "$TMPFILE"

if [ ! -s "$TMPFILE" ]; then
  echo "Aucun membre trouvé ($GROUP@$REALM)."
  exit 0
fi

echo "$(wc -l < "$TMPFILE") utilisateurs dans le groupe $GROUP@$REALM."

# Création des pools et application du role
while read -r USER; do
  USERNAME="${USER%@*}"
  POOLNAME="$PREFIX$USERNAME"

  # Création du pool s'il n'existe pas déjà
  if ! pveum pool list --noborder | awk '{print $1}' | grep -q "$POOLNAME"; then
    echo "Création du pool $POOLNAME pour $USER"
    pveum pool add "$POOLNAME" --comment "Pool utilisateur $USER"
  fi

  # Ajout du rôle si pas déjà attribué
  if ! pveum acl list --noborder | grep -q "/pool/$POOLNAME"; then
    echo "Application du rôle $ROLE sur /pool/$POOLNAME pour $USERNAME"
    pveum acl modify "/pool/$POOLNAME" --users "$USERNAME@$REALM" --role "$ROLE" --propagate 0
  fi

done < "$TMPFILE"

echo "Pools créés"


# Marquage des pools et extinction des VMs des utilisateurs plus membres
echo "Marquage des pools obsolètes"

for POOL in $(pveum pool list --noborder | awk '{print $1}' | grep "$PREFIX"); do
  USERNAME="${POOL#$PREFIX}"
  USERFULL="$USERNAME@$REALM"

  # Utilisateur plus membre du groupe

  if ! grep -q "$USERFULL" "$TMPFILE"; then
    echo "Utilisateur $USERFULL non membre du groupe)"

    # Creation du pool d'archivage si non vide
    pveum pool add "$RMPREFIX-$USERNAME" --comment "Pool supprimé $USER"

    # Extinction des VMs appartenant au pool
    VMLIST=$(pvesh get /pools/$POOL --noborder | grep members | grep -o '"id":"qemu/[0-9]\+"' | cut -d'/' -f2 | tr -d '"')

    for VMID in $VMLIST; do
      echo "Extinction et déplacement de la VM $VMID..."
      qm stop "$VMID" 2>/dev/null
      pveum pool modify "$RMPREFIX-$USERNAME" --vms $VMID --allow-move 1
    done

    pveum pool delete $POOL
  fi
done

rm $TMPFILE
echo "Synchronisation terminée pour le groupe $GROUP@$REALM ."

exit 0